### ISSUE TITLE
Ethereum logo with useless link in whitelisted box

### ISSUE THREAD

**Issue by chrisd08** [chrisd08/Cryptov8#2]
There is a an Ethereum logo in the 'Get whitelisted' box, which appears to have a hyperlink that just points to - www.cryptov8.com/#ethereum.  Is that correct?  It just seem to bring you back to the main page.

**Comment by chrisd08** [comment]
I've prevented the link causing the page refresh and center aligned it, is it worth keeping this if we are only accepting Ethereum as payment method?

**Comment by jonfinov8** [comment]
I think we'll keep it as is for now.
